$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows general alignment configuration

properties:
  # paths to store results
  fastq_dir:
    description: directory inside the result dir where to store the workflow fastqs
    default: FASTQ
    type: string
  trimmed_dir:
    description: directory inside the result dir where to store the workflow trimmed fastqs
    default: FASTQ
    type: string
  trimmedqc_dir:
    description: directory inside the result dir where to store the workflow trimming quality controls
    default: trimmed_qc
    type: string
  dedup_dir:
    description: directory inside the result dir where to store the workflow deduplicated alignment
    default: dedup
    type: string


  # trim_galore parameters
  trim_galore:
    description: trim_galore settings (note that the adapter is autodetected, so you do not have to set it here)
    default: --quality 10 --length 20 --consider_already_trimmed 10
    type: string


  # aligner
  aligner:
    description: which aligner to use
    type: object
    properties:
      bowtie2:
        properties:
          bowtie2_params: {type: string}
      bwa:
        properties:
          bwa_algo:       {type: string}
      hisat2:
        properties:
          hisat2_params:  {type: string}
      salmon:
        properties:
          salmon_index:   {type: string}
          salmon_aln:     {type: string}
    minProperties: 1
    additionalProperties: false
    default:
      bwa:
        bwa_algo: bwtsw


  # samtools index
  samtools_index:
    description: samtools index settings
    default: ''
    type: string

  # picard markduplicates
  markduplicates:
    description: the parameters of picard markduplicates
    default: REMOVE_DUPLICATES=false -Xms4G -Xmx6G MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=999
    type: string
