$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows gene expression configuration

properties:
  # scope of analysis: create a trackhub or only align and/or quantify (and create gene counts)
  create_trackhub:
    description: Run aligning to the genome or only output a counts table
    default: True
    enum: [True, False]

  deeptools:
    description: option flags for bam to bigwig conversions with deeptools bamCoverage
    default: --samFlagExclude 1024 # exclude duplicates marked by Picard
  filter_bam_by_strand:
    description: split bigwigs by strand?
    default: True
    enum: [True, False]
