# tab-separated file of the samples
samples: samples.tsv


# contact info for multiqc report and trackhub
email: yourmail@here.com


# pipeline file locations
result_dir: /mnt/ocimum/vol/dick  # where to store results
genome_dir: /mnt/ocimum/vol/genomes  # where to look for or download the genomes


# peak caller
peak_caller:
  macs2:
      --keep-dup 1 --buffer-size 10000

combine_replicates: fisher
remove_blacklist: True
minqual: 10

# which aligner to use with the option to specify own parameters
aligner:
  bwa:
    index:  # parameters for indexing
      '-a bwtsw'
    align:  # parameters for alignment
      ''

# or use 'our' default parameters
# aligner:
#   bwa
