$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows downloading configuration

properties:
  # paths to download and dump to
  sra_dir:
    description: directory where to store the workflow sras (defaults inside the result dir)
    default: sra
    type: string
  fastq_dir:
    description: directory where to store the workflow fastqs (defaults inside the result dir)
    default: fastq
    type: string

  # NCBI e-utilities key
  ncbi_key:
    description: e-utilities key for faster lookup interval
    type: string
  ncbi_requests:
    description: the number of lookups per second the key permits
    type: integer

  # downloading through ascp
  ascp_path:
    description: the pipeline supports downloading through ascp if this variable is set.
    type: string
  ascp_key:
    description: the public key of ascp
    type: string

  # fastq-dump parameters
  split:
    description: fastq-dump parameters when splitting reads (paired-end)
    default: --split-files --skip-technical --dumpbase --readids --clip --read-filter pass --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+'
    type: string
  splot:
    description: fastq-dump parameters when splotting reads (single-end)
    default: --split-spot  --skip-technical --dumpbase --readids --clip --read-filter pass --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+'
    type: string
