# tab-separated file of the samples
samples: samples.tsv


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ./  # where to look for or download the genomes


# which aligner to use with the option to specify own parameters
aligner:
  hisat2:
    index:  # parameters for indexing
      ''
    align:  # parameters for alignment
      '-X 2000 --no-spliced-alignment'

# file extensions
fqext1: R1
fqext2: R2

#options of rules:
snaptools_opt: --min-mapq=30  --min-flen=0  --max-flen=1000  --keep-chrm=TRUE  --keep-single=FALSE  --keep-secondary=FALSE  --overwrite=True  --min-cov=100  --verbose=True
bin_opt: --bin-size-list 5000 --verbose=True
