# tab-separated file of the samples
samples: samples.tsv


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ../../Jenkins  # where to look for or download the genomes
fastq_dir: ../../Jenkins/tinyfastq


# produce bams, bigwigs and QC statistics?
run_alignment: False

# which method to use in order to generate the counts (salmon or star)
quantifier: star

### package Tximeta must be updated (to 1.4.4 or higher) on conda before salmon works again ###

## which method to use in order to generate the counts (salmon or star)
#quantifier:
#  salmon:
#    quantifier_index_flags: '-k 31'
#    quantifier_flags: '--seqBias --gcBias --validateMappings --recoverOrphans'
#    decoy_aware_index: True # salmon only. Generating a decoy requires ~65 GB RAM for GRCh38 (default is False)

# differential expression analysis
diffexp:
  deseq2:
    DE_params:
      multiple_testing_procedure: IHW # options: BH/IHW. Default is BH
      alpha_value: 0.05
      shrinkage_estimator: apeglm
    contrasts:
      - 'disease_control_disease'
      - 'stage_2_1'
      - 'stage_all_1'
