# tab-separated file of the samples
samples: samples.tsv


# contact info for multiqc report and trackhub
email: yourmail@here.com


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ./   # where to look for or download the genomes


# peak callers (supported peak callers are macs2, and genrich, and hmmratac is not fully supported yet)
peak_caller:
  macs2:
      --shift -100 --extsize 200 --nomodel --keep-dup 1 --buffer-size 10000
#  genrich:
#      -y -j -r
#  hmmratac:
#      ""

combine_replicates: fisher
remove_blacklist: True
remove_mito: True
tn5_shift: True
minqual: 10

# which aligner to use with the option to specify own parameters
# aligner:
#   bwa:
#     index:  # parameters for indexing
#       '-a bwtsw'
#     align:  # parameters for alignment
#       ''

# or use 'our' default parameters
aligner: bwa
