# tab-separated file of the samples
samples: ../../Jenkins/rna_seq/dag_samples.tsv

# pipeline file locations
result_dir: ../../Jenkins_results  # where to store results
genome_dir: ../../Jenkins_results  # where to look for or download the genomes

# produce bigwigs and a trackhub?
create_trackhub: False

# produce MultiQC output?
create_qc_report: False

# differential expression analysis
diffexp: # which analysis to use (DESeq2 or None, default: None)
  deseq2:
    contrasts:
      - batch + stage_2_1
