# tab-separated file of the samples
samples: samples.tsv


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ./  # where to look for or download the genomes


# which aligner to use
aligner: bwa
